# config/packages/security.yaml
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        super_admin: # Firewall for the Super Admin area
            pattern: ^/superadmin # All URLs starting with /superadmin
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: superadmin_login
                check_path: superadmin_login
                default_target_path: superadmin_dashboard
                username_parameter: email      # ADD THIS LINE
                password_parameter: password    # ADD THIS LINE
            logout:
                path: superadmin_logout
                target: superadmin_login
        main: # Default firewall for other parts of the app (company users later)
            lazy: true
            provider: app_user_provider
            # ... (main firewall config)

    role_hierarchy: # <--- CORRECT PLACEMENT: Top-level key under security
        ROLE_SUPER_ADMIN: [ROLE_USER]
        # ROLE_COMPANY_ADMIN: [ROLE_USER] # You can uncomment and use this later

    access_control:
        - { path: ^/superadmin/login, roles: PUBLIC_ACCESS }
        - { path: ^/superadmin, roles: ROLE_SUPER_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    # ... (test configuration remains the same)